# Generated by Django 4.0.5 on 2022-06-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Posts', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
