# Generated by Django 4.0.5 on 2022-06-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_RegLog', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
